version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: staging
    ports:
      - "3360:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  localstack:
    image: localstack/localstack
    container_name: localstack
    environment:
      - SERVICES=s3
      - DEBUG=1
    ports:
      - "4566:4566"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow
    restart: always
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__DEFAULT_USER="admin"
      - AIRFLOW__WEBSERVER__DEFAULT_PASSWORD="admin"
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dags/src:/opt/airflow/dags/src
      - ./data/raw:/opt/airflow/dags/data/raw
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: ["airflow", "standalone"]

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api
    restart: always
    depends_on:
      - mysql
      - mongodb
      - localstack
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=staging
      - MYSQL_PORT=3306
      - MONGO_URI=mongodb://mongodb:27017/
      - S3_ENDPOINT_URL=http://localstack:4566
    ports:
      - "8000:8000"
    volumes:
      - ./api:/opt/api
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]



volumes:
  mysql_data:
  mongo_data:
